name: Backend

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
  pull_request:
  schedule:
    - cron: '0 6 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v7

      - name: Detect Changes
        uses: dorny/paths-filter@v4
        id: filter
        with:
          filters: |
            backend:
              - 'backend/**'
              - 'api/**'
              - '.github/workflows/backend.yml'

  backend-lint:
    needs: changes
    if: ${{ github.event_name != 'pull_request' || needs.changes.outputs.backend == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v7

      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version-file: './backend/go.mod'

      - name: Lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.14.0
          working-directory: backend
          args: --timeout=3m --config=./.golangci.yaml

  backend-unit-test:
    needs: changes
    if: ${{ github.event_name != 'pull_request' || needs.changes.outputs.backend == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v7

      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version-file: './backend/go.mod'

      - name: Run Unit Tests
        run: make -C backend test-unit

  backend-integration-test:
    needs: changes
    if: ${{ github.event_name != 'pull_request' || needs.changes.outputs.backend == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v7

      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version-file: './backend/go.mod'

      - name: Run Integration Tests
        run: make -C backend test-integration
